---
name: ci
on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    types:
      # Default PR events + ready_for_review
      # so checks run when PR is pulled out of draft
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
      - release-*
jobs:
  workflow-arke:
    runs-on: golang:1.25.7-trixie
    permissions:
      contents: write
      id-token: write
    env:
      GOMEMLIMIT: 2GiB
    services:
      docker:
        image: docker:dind # Use the official Docker-in-Docker image
        options: --privileged --shm-size=2g # The --privileged flag is required for DinD to function
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # See https://github.com/marketplace/actions/super-linter
      # dockerfile, git-merge-conflict markers, github actions, golangci-lint, licenses (trivy),
      # markdown, proto buf, secrets, shellcheck, yaml
      - name: super-linter
        uses: super-linter/super-linter@v8.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
